spring.application.name=trainSerie
spring.config.import=optional:file:.env[.properties]

server.port=8081
spring.data.mongodb.uri=${MONGO_URI}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Tag global — aparece em todas as métricas no Grafana
management.metrics.tags.application=register-athlete
